theme: jekyll-theme-cayman
title: Nod - Reactions for Google Meet
description: Nod allows team members to send real-time reactions to presenters and speakers during meetings on Google Meet.
github: false
