connectionTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: hand-signals-connections-prod
    attributeDefinitions:
      - AttributeName: connectionID
        AttributeType: S
      - AttributeName: meetingID
        AttributeType: S
    keySchema:
      - AttributeName: connectionID
        KeyType: HASH
      - AttributeName: meetingID
        KeyType: RANGE
    globalSecondaryIndexes:
      - IndexName: meetingIndex
        KeySchema:
          - AttributeName: meetingID
            KeyType: HASH
          - AttributeName: connectionID
            KeyType: RANGE
        Projection:
          ProjectionType: "KEYS_ONLY"
    region: eu-west-2

teamsTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: hand-signals-teams-prod
    attributeDefinitions:
      - AttributeName: teamName
        AttributeType: S
    keySchema:
      - AttributeName: teamName
        KeyType: HASH
    region: eu-west-2

websocketApi:
  component: "@serverless/backend-socket"
  inputs:
    name: hand-signals-websocket-prod
    stage: prod
    description: Hand Signals - prod websocket
    region: eu-west-2
    memory: 128
    timeout: 10
    env:
      connectionDb: ${connectionTable.name}
      teamsDb: ${teamsTable.name}
    code:
      src: ../../backend/socket
